services:
    shopware_search.anhchor.listener:
        class: Shopware\Devdocs\AnchorListener
        tags:
            - { name: kernel.event_subscriber }

    league.commonmark.tablextension:
        class: League\CommonMark\Extension\Table\TableExtension
        tags:
            - { name: sculpin_commonmark.extension }

    shopware_devdocs.twig_extension:
        class: Shopware\Devdocs\TwigExtension
        arguments:
            - '%kernel.environment%'
        tags:
            - { name: twig.extension }
